version: '3.8'

services:
  bot:
    build: .
    container_name: foosball_bot
    environment:
      - API_TOKEN=${API_TOKEN}
      - DB_PATH=${DB_PATH}
      - ROOTADMIN_INFO=${ROOTADMIN_INFO}
    volumes:
      - ./app/foosball.db:/app/foosball.db
    restart: unless-stopped
